[workspace]
authors = ["Nilesh <4813079+nilesh-patil@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "nilesh"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
ruby = ">=3.4.4,<4"
python = "==3.12.0"
compilers = "*"
make = "*"

[pypi-dependencies]
pandas = ">=2.3.1, <3"
pybtex = ">=0.25.1, <0.26"
pandoc = ">=2.4, <3"
